spring.application.name=tmbackend
server.port=8888

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console 

spring.jackson.time-zone=Europe/London
spring.jackson.locale=en_EN

# SEE https://springdoc.org/#Introduction
springdoc.api-docs.path=/api-docs
springdoc.paths-to-match=/api/**
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.writer-with-order-by-keys=true
springdoc.swagger-ui.operationsSorter=method
